{% set version = "0.1.pre" %}
{% set commit = "257e65b8136463b716eeeee53836aec9916d0c15" %}

package:
  name: parquet-cpp
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/apache/parquet-cpp/archive/{{ commit }}.tar.gz
  sha256: e59807491cb25e7ad54f390b175d0dc799130913054d831b792885832bd23d00

build:
  number: 11
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - arrow-cpp
    - boost 1.63.*
    - cmake
    - zlib 1.2.*
    - snappy
    - brotli
    - thrift-cpp

  run:
    - arrow-cpp

test:
  commands:
    - test -f $PREFIX/lib/libparquet.so  # [linux]
    - test -f $PREFIX/lib/libparquet_arrow.so  # [linux]
    - test -f $PREFIX/lib/libparquet.dylib  # [osx]
    - test -f $PREFIX/lib/libparquet_arrow.dylib  # [osx]
    - test -f $PREFIX/include/parquet/api/reader.h

about:
  home: http://github.com/apache/parquet-cpp
  license: Apache 2.0
  summary: 'C++ libraries for the Apache Parquet file format'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
