{% set version = "1.1.0" %}
{% set commit = "116e80e06adce9b7298975b6b645b336445a2ff8" %}

# NOTE(wesm): When updating the build, please remember also to update the
# pinned Arrow version. We are letting parquet-cpp build its own Apache Arrow
# so that we do not have to update conda-packages for Arrow before we can
# update this package. So if there is an ABI change in Arrow, we can update
# this package faster

package:
  name: parquet-cpp
  version: {{ version }}

source:
  fn: apache-parquet-cpp-{{ version }}.tar.gz
  url: https://github.com/apache/parquet-cpp/archive/{{ commit }}.tar.gz
  sha256: a8e77b53c26c56ff2d5043543ba62e7c4627ba786a7162c5b557fd6607c8f472

build:
  number: 2
  skip: true  # [win and not (py35 and win64)]
  features:
    - vc14  # [win and py35]

requirements:
  build:
    - toolchain
    - boost-cpp 1.63.*
    - cmake
    - zlib 1.2.*
    - snappy
    - brotli
    - thrift-cpp
    - arrow-cpp 0.4.*
    - python            # [win]

  run:
    - arrow-cpp 0.4.*

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]

  commands:
    - test -f $PREFIX/lib/libparquet.so                                       # [linux]
    - test -f $PREFIX/lib/libparquet_arrow.so                                 # [linux]
    - test -f $PREFIX/lib/libparquet.dylib                                    # [osx]
    - test -f $PREFIX/lib/libparquet_arrow.dylib                              # [osx]
    - test -f $PREFIX/include/parquet/api/reader.h                            # [unix]
    - if not exist %PREFIX%\\Library\\include\\parquet\\api\\reader.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\parquet.dll exit 1                 # [win]
    - if not exist %PREFIX%\\Library\\lib\\parquet.lib exit 1                 # [win]
    - if not exist %PREFIX%\\Library\\lib\\parquet_static.lib exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\parquet_arrow.dll exit 1           # [win]
    - if not exist %PREFIX%\\Library\\lib\\parquet_arrow.lib exit 1           # [win]
    - if not exist %PREFIX%\\Library\\lib\\parquet_arrow_static.lib exit 1    # [win]

about:
  home: http://github.com/apache/parquet-cpp
  license: Apache 2.0
  summary: 'C++ libraries for the Apache Parquet file format'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - leifwalsh
    - jreback
    - cpcloud
