{% set version = "1.1.0pre" %}
{% set commit = "893af978a9184a17ca44cfbe44a786460e56a49a" %}

# NOTE(wesm): When updating the build, please remember also to update the
# pinned Arrow version. We are letting parquet-cpp build its own Apache Arrow
# so that we do not have to update conda-packages for Arrow before we can
# update this package. So if there is an ABI change in Arrow, we can update
# this package faster

package:
  name: parquet-cpp
  version: {{ version }}

source:
  fn: apache-parquet-cpp-{{ version }}.tar.gz
  url: https://github.com/apache/parquet-cpp/archive/{{ commit }}.tar.gz
  sha256: ea6cb7870504717893d7dc78448de59b91cfbf4c7f33a2cb07ff3a0dacea2961

build:
  number: 1
  skip: true  # [win]

# TODO(wesm): Not including arrow-cpp in the requirements because that
# introduces a build-time dependency on up-to-date conda-forge packages. While
# these libraries are changing fast, this does more harm than good to developer
# productivity. When things are changing less often, we should pin a precise
# Arrow runtime version here

# run:
#   - arrow-cpp 0.3.*

requirements:
  build:
    - toolchain
    - boost-cpp 1.63.*
    - cmake
    - zlib 1.2.*
    - snappy
    - brotli
    - thrift-cpp

test:
  commands:
    - test -f $PREFIX/lib/libparquet.so  # [linux]
    - test -f $PREFIX/lib/libparquet_arrow.so  # [linux]
    - test -f $PREFIX/lib/libparquet.dylib  # [osx]
    - test -f $PREFIX/lib/libparquet_arrow.dylib  # [osx]
    - test -f $PREFIX/include/parquet/api/reader.h

about:
  home: http://github.com/apache/parquet-cpp
  license: Apache 2.0
  summary: 'C++ libraries for the Apache Parquet file format'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - leifwalsh
