{% set version = "1.1.0pre" %}
{% set commit = "62905f90c75f8891f2e91cb39a29efe56afed614" %}

# NOTE(wesm): When updating the build, please remember also to update the
# pinned Arrow version. We are letting parquet-cpp build its own Apache Arrow
# so that we do not have to update conda-packages for Arrow before we can
# update this package. So if there is an ABI change in Arrow, we can update
# this package faster

package:
  name: parquet-cpp
  version: {{ version }}

source:
  fn: apache-parquet-cpp-{{ version }}.tar.gz
  url: https://github.com/apache/parquet-cpp/archive/{{ commit }}.tar.gz
  sha256: badb29c24317465375783a55989a6acb6bae6a87da6952a04a5f84cf3bde599f

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - boost-cpp 1.63.*
    - cmake
    - zlib 1.2.*
    - snappy
    - brotli
    - thrift-cpp

  run:
    - arrow-cpp 0.3.*

test:
  commands:
    - test -f $PREFIX/lib/libparquet.so  # [linux]
    - test -f $PREFIX/lib/libparquet_arrow.so  # [linux]
    - test -f $PREFIX/lib/libparquet.dylib  # [osx]
    - test -f $PREFIX/lib/libparquet_arrow.dylib  # [osx]
    - test -f $PREFIX/include/parquet/api/reader.h

about:
  home: http://github.com/apache/parquet-cpp
  license: Apache 2.0
  summary: 'C++ libraries for the Apache Parquet file format'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - leifwalsh
