{% set version = "1.1.0pre" %}
{% set commit = "e67d49bc0b5d199326c1a138ac53ddde3ebbebd4" %}

# NOTE(wesm): When updating the build, please remember also to update the
# pinned Arrow version. We are letting parquet-cpp build its own Apache Arrow
# so that we do not have to update conda-packages for Arrow before we can
# update this package. So if there is an ABI change in Arrow, we can update
# this package faster

package:
  name: parquet-cpp
  version: {{ version }}

source:
  fn: apache-parquet-cpp-{{ version }}.tar.gz
  url: https://github.com/apache/parquet-cpp/archive/{{ commit }}.tar.gz
  sha256: 78c562fb345f9592ef52238c35ecb859c215640ccb178810fa66a098ab2443e6

build:
  number: 4
  skip: true  # [win and not (py35 and win64)]
  features:
    - vc14  # [win and py35]

# TODO(wesm): Not including arrow-cpp in the requirements because that
# introduces a build-time dependency on up-to-date conda-forge packages. While
# these libraries are changing fast, this does more harm than good to developer
# productivity. When things are changing less often, we should pin a precise
# Arrow runtime version here

# run:
#   - arrow-cpp 0.3.*

requirements:
  build:
    - toolchain
    - boost-cpp 1.63.*
    - cmake
    - zlib 1.2.*
    - snappy
    - brotli
    - thrift-cpp
    - python            # [win]

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]

  commands:
    - test -f $PREFIX/lib/libparquet.so                                       # [linux]
    - test -f $PREFIX/lib/libparquet_arrow.so                                 # [linux]
    - test -f $PREFIX/lib/libparquet.dylib                                    # [osx]
    - test -f $PREFIX/lib/libparquet_arrow.dylib                              # [osx]
    - test -f $PREFIX/include/parquet/api/reader.h                            # [unix]
    - if not exist %PREFIX%\\Library\\include\\parquet\\api\\reader.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\parquet.dll exit 1                 # [win]
    - if not exist %PREFIX%\\Library\\lib\\parquet.lib exit 1                 # [win]
    - if not exist %PREFIX%\\Library\\lib\\parquet_static.lib exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\parquet_arrow.dll exit 1           # [win]
    - if not exist %PREFIX%\\Library\\lib\\parquet_arrow.lib exit 1           # [win]
    - if not exist %PREFIX%\\Library\\lib\\parquet_arrow_static.lib exit 1    # [win]

about:
  home: http://github.com/apache/parquet-cpp
  license: Apache 2.0
  summary: 'C++ libraries for the Apache Parquet file format'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - leifwalsh
